version: "3.9"
services: 
    web-server:
      image: nginx:1.21.1
      container_name: webdev-nginx
      ports:
        - "90:90"
      networks:
        - web-dev
      volumes:
        - ./confs/servers/:/etc/nginx/conf.d/
        - ./controle_veiculos:/var/www/controle_veiculos
    php:
      build:
        dockerfile: ./php.dockerfile
        context: .
      image: php7.4-fpm
      container_name: webdev-php
      volumes: 
        - ./controle_veiculos:/var/www/controle_veiculos
      ports: 
        - "9000:9000"
      networks: 
        - web-dev

    db:
      image: mysql:8.0.26
      container_name: webdev-mysql
      volumes: 
        - ./confs/mysql_db:/var/lib/mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test_db
        MYSQL_USER: devuser
        MYSQL_PASSWORD: devpass
      ports:
        - "3307:3307"
      networks: 
        - web-dev

networks: 
      web-dev:
        driver: bridge