version: '3.9'
services:
  web-server:
    image: nginx:1.21.1
    container_name: nginx
    ports:
      - "5000:5000"
    networks:
      - web-dev
    volumes:
      - ./confs/servers/:/etc/nginx/conf.d/
      - ./nuxt-app:/var/www/nuxt-app
  app:
    build:
      dockerfile: ./nuxt.dockerfile
      context: .
    ports:
      - '5000:5000'
  db:
    image: mysql:8.0.26
    container_name: nuxt-mysql
    restart: unless-stopped
    volumes: 
      - ../confs/mysql_db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3307:3307"
    networks: 
      - web-dev
networks: 
      web-dev:
        driver: bridge
